###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: laravelcuritiba-memcached

    redis:
      image: redis:alpine
      container_name: laravelcuritiba-redis

    mariadb:
      image: mariadb:10.4
      container_name: laravelcuritiba-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "1028:3306"

    webserver:
      image: nginx:alpine
      container_name: laravelcuritiba-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laravelcuritiba-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

